#include <map>
#include <string>

const std::map<std::string, std::string> wmList = {
                    {"i3", "i3"},
                    {"bspwm", "bspwm"},
                    {"openbox", "openbox"},
                    {"gnome-shell", "Mutter"},
                    {"kwin_x11", "KWin (X11)"},
                    {"kwin_wayland", "KWin (Wayland)"},
                    {"dwm", "dwm"},
                    {"sowm", "sowm"},
                    {"dwl", "dwl"},
                    {"weston", "weston"},
                    {"wayfire", "wayfire"},
                    {"labwc", "labwc"},
                    {"sway", "sway"},
                    {"hikari", "hikari"},
                    {"motorcar", "motarcar"},
                    {"catwm", "catwm"},
                    {"fvwm", "fvwm"},
                    {"2bwm", "2bwm"},
                    {"monsterwm", "monsterwm"},
                    {"tinywm", "tinywm"},
                    {"x11fs", "x11fs"},
                    {"xmonad", "xmonad"},
                    {"awesome", "awesome"},
                    {"fireplace", "fireplace"},
                    {"mazecompositor", "mazecompositor"},
                    {"way-cooler", "way-cooler"},
};
